version: "3.9"  
services: 

  webserver:
    build: 
      context: ./nginx
    tty: true
    depends_on:
      - app
    networks:
      - redenode
    ports:
      - 8080:80

  app:
    build:
      context: ./app
    container_name: app
    networks:
      - redenode
    tty: true  
   
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 45s
            interval: 10s
            retries: 10
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER:root
    networks:
      - redenode

networks:
  redenode:
    driver: bridge